Repository High-Quality-Coffee/JGJW-Express, pull requests merged in 2025-03, with the labels that each got.

#5 공통 설정 : 필요한 설정 파일, 의존성 추가
  build.gradle
  common/src/main/java/com/zgzg/common/config/JpaConfig.java
Labels: feature

#11 feat: Hub - 도메인 구조 설계 및 Hub 생성 API 구현 {#8}
  .gitignore
  common/src/main/java/com/zgzg/common/response/Code.java
  gateway/src/main/resources/application.yml
  hub/build.gradle
  hub/src/main/java/com/zgzg/hub/HubApplication.java
  hub/src/main/java/com/zgzg/hub/application/HubService.java
  hub/src/main/java/com/zgzg/hub/application/res/CreateHubResDTO.java
  hub/src/main/java/com/zgzg/hub/domain/entity/Hub.java
  hub/src/main/java/com/zgzg/hub/domain/repository/HubRepository.java
  hub/src/main/java/com/zgzg/hub/presentation/HubController.java
  hub/src/main/java/com/zgzg/hub/presentation/req/CreateHubReqDTO.java
  hub/src/main/resources/application.yml
  hub/src/test/java/com/zgzg/hub/HubApplicationTests.java
  settings.gradle
Labels: feature, 🎨structure

#13 주문_주문 RUD, Search API 구현
  .gitignore
  common/build.gradle
  common/src/main/java/com/zgzg/common/config/JpaConfig.java
  common/src/main/java/com/zgzg/common/response/Code.java
  order/build.gradle
  order/src/main/java/com/zgzg/order/application/dto/global/PageableResponse.java
  order/src/main/java/com/zgzg/order/application/dto/res/OrderDetaiListDTO.java
  order/src/main/java/com/zgzg/order/application/dto/res/OrderDetailDTO.java
  order/src/main/java/com/zgzg/order/application/dto/res/OrderDetailResponseDTO.java
  order/src/main/java/com/zgzg/order/application/dto/res/OrderResponseDto.java
  order/src/main/java/com/zgzg/order/application/service/OrderService.java
  order/src/main/java/com/zgzg/order/domain/entity/Order.java
  order/src/main/java/com/zgzg/order/domain/entity/OrderDetail.java
  order/src/main/java/com/zgzg/order/domain/entity/OrderStatus.java
  order/src/main/java/com/zgzg/order/domain/repo/OrderRepository.java
  order/src/main/java/com/zgzg/order/infrastructure/repo/OrderDetailJpaRepository.java
  order/src/main/java/com/zgzg/order/infrastructure/repo/OrderJpaRepository.java
  order/src/main/java/com/zgzg/order/infrastructure/repo/OrderJpaRepositoryCustom.java
  order/src/main/java/com/zgzg/order/infrastructure/repo/OrderJpaRepositoryCustomImpl.java
  order/src/main/java/com/zgzg/order/infrastructure/repo/OrderRepositoryImpl.java
  order/src/main/java/com/zgzg/order/presentation/controller/OrderController.java
  order/src/main/java/com/zgzg/order/presentation/dto/req/CreateOrderRequestDto.java
  order/src/main/java/com/zgzg/order/presentation/dto/req/SearchCriteria.java
Labels: ✨feature

#24 feat: Route(허브 경로) 데이터 저장 로직 구현
  hub/src/main/java/com/zgzg/hub/HubApplication.java
  hub/src/main/java/com/zgzg/hub/application/route/client/RouteClient.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/OrganizedRouteDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/ProcessedRouteDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/service/NaverRouteService.java
  hub/src/main/java/com/zgzg/hub/application/route/service/RouteProcessingService.java
  hub/src/main/java/com/zgzg/hub/application/route/service/RouteStorageService.java
  hub/src/main/java/com/zgzg/hub/config/NaverDirectionConfig.java
  hub/src/main/java/com/zgzg/hub/domain/entity/Route.java
  hub/src/main/java/com/zgzg/hub/domain/repository/RouteRepository.java
  hub/src/main/java/com/zgzg/hub/infrastructure/client/NaverDirectionClient.java
  hub/src/main/java/com/zgzg/hub/infrastructure/client/dto/NaverRouteResDTO.java
  hub/src/main/java/com/zgzg/hub/infrastructure/client/dto/RouteDTO.java
  hub/src/main/java/com/zgzg/hub/presentation/RouteController.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/hubData.sql
  hub/src/test/java/com/zgzg/hub/application/NaverRouteServiceTest.java
Labels: ✨feature

#28 Delivery CRUD, Search, BaseEntity UserAudit 추가
  common/src/main/java/com/zgzg/common/config/JpaConfig.java
  common/src/main/java/com/zgzg/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/zgzg/common/response/Code.java
  common/src/main/java/com/zgzg/common/utils/UserAuditorAware.java
  delivery/build.gradle
  delivery/src/main/java/com/zgzg/delivery/DeliveryApplication.java
  delivery/src/main/java/com/zgzg/delivery/application/dto/res/DeliveryResponseDTO.java
  delivery/src/main/java/com/zgzg/delivery/application/dto/res/DeliveryRouteLogsResponseDTO.java
  delivery/src/main/java/com/zgzg/delivery/application/dto/res/DeliveryRouteResponseDTO.java
  delivery/src/main/java/com/zgzg/delivery/application/dto/res/PageableResponse.java
  delivery/src/main/java/com/zgzg/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/zgzg/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/zgzg/delivery/domain/entity/DeliveryRouteLog.java
  delivery/src/main/java/com/zgzg/delivery/domain/entity/DeliveryStatus.java
  delivery/src/main/java/com/zgzg/delivery/domain/repo/DeliveryRepository.java
  delivery/src/main/java/com/zgzg/delivery/domain/repo/DeliveryRouteLogRepository.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/configuration/GlobalConfig.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/configuration/SecurityConfig.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/repo/DeliveryJpaRepository.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/repo/DeliveryJpaRepositoryCustom.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/repo/DeliveryJpaRepositoryCustomImpl.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/repo/DeliveryRepositoryImpl.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/repo/DeliveryRouteLogJpaRepository.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/repo/DeliveryRouteLogRepositoryImpl.java
  delivery/src/main/java/com/zgzg/delivery/presentation/DeliveryController.java
  delivery/src/main/java/com/zgzg/delivery/presentation/dto/global/SearchCriteria.java
  delivery/src/main/java/com/zgzg/delivery/presentation/dto/req/CreateDeliveryRequestDTO.java
  delivery/src/main/java/com/zgzg/delivery/presentation/dto/req/CreateDeliveryRoute.java
  delivery/src/main/resources/application.yml
  delivery/src/test/java/com/zgzg/delivery/DeliveryApplicationTests.java
  gateway/src/main/resources/application.yml
  order/src/main/java/com/zgzg/order/application/dto/res/OrderResponseDTO.java
  settings.gradle
Labels: ✨feature

#31 Feat: Redis 저장 및 캐싱 처리 구현, 경로 조회 API 구현
  hub/build.gradle
  hub/src/main/java/com/zgzg/hub/application/hub/HubService.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/CreateHubResDTO.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/HubResDTO.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/PageHubsResDTO.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/UpdateHubResDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/RedisRouteDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/RoutesDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/service/RouteService.java
  hub/src/main/java/com/zgzg/hub/application/route/service/RouteStorageService.java
  hub/src/main/java/com/zgzg/hub/config/AsyncConfig.java
  hub/src/main/java/com/zgzg/hub/config/RedisConfig.java
  hub/src/main/java/com/zgzg/hub/domain/entity/Route.java
  hub/src/main/java/com/zgzg/hub/domain/repository/RouteRepository.java
  hub/src/main/java/com/zgzg/hub/infrastructure/redis/RedisHashUtil.java
  hub/src/main/java/com/zgzg/hub/presentation/RouteController.java
  hub/src/main/java/com/zgzg/hub/presentation/hub/HubController.java
  hub/src/main/java/com/zgzg/hub/presentation/hub/req/CreateHubReqDTO.java
  hub/src/main/java/com/zgzg/hub/presentation/hub/req/UpdateHubReqDTO.java
  hub/src/main/java/com/zgzg/hub/presentation/route/RouteController.java
  hub/src/main/resources/application.yml
  hub/src/main/resources/sql/hubData.sql
Labels: ✨feature, ♻️refactor

#34 feat: delivery - 배송 상태 변경 및 경로 기록 api 구현 #22
  delivery/src/main/java/com/zgzg/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/zgzg/delivery/domain/entity/Delivery.java
  delivery/src/main/java/com/zgzg/delivery/domain/entity/DeliveryRouteLog.java
  delivery/src/main/java/com/zgzg/delivery/presentation/DeliveryController.java
Labels: ✨feature

#38 refactor: 업체 조회 기능 수정
  company/src/main/java/com/zgzg/company/domain/Company.java
  company/src/main/java/com/zgzg/company/presentation/dto/CompanyResponseDTO.java
  company/src/main/java/com/zgzg/company/presentation/dto/CreateCompanyRequestDTO.java
Labels: ♻️refactor

#41 Refactor: 경로 데이터 허브명 추가 / delete Null만 조회,검색 추가 / deletedBy 적용
  hub/src/main/java/com/zgzg/hub/application/hub/HubService.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/OrganizedRouteDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/ProcessedRouteDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/RedisRouteDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/dto/RoutesDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/service/NaverRouteService.java
  hub/src/main/java/com/zgzg/hub/application/route/service/RouteProcessingService.java
  hub/src/main/java/com/zgzg/hub/application/route/service/RouteStorageService.java
  hub/src/main/java/com/zgzg/hub/application/route/service/facade/RouteService.java
  hub/src/main/java/com/zgzg/hub/domain/entity/Hub.java
  hub/src/main/java/com/zgzg/hub/domain/entity/Route.java
  hub/src/main/java/com/zgzg/hub/infrastructure/client/naver/NaverDirectionClient.java
  hub/src/main/java/com/zgzg/hub/infrastructure/client/naver/dto/NaverRouteResDTO.java
  hub/src/main/java/com/zgzg/hub/infrastructure/client/naver/dto/RouteDTO.java
  hub/src/main/java/com/zgzg/hub/presentation/hub/HubController.java
  hub/src/main/java/com/zgzg/hub/presentation/route/RouteController.java
  hub/src/main/java/com/zgzg/hub/presentation/route/RouteTestController.java
Labels: ♻️refactor

#42 feature: 메세지 검색 기능 추가
  ai/src/main/java/com/zgzg/ai/application/service/SlackService.java
  ai/src/main/java/com/zgzg/ai/domain/Message.java
  ai/src/main/java/com/zgzg/ai/domain/persistence/MessageReposiroty.java
  ai/src/main/java/com/zgzg/ai/domain/persistence/SlackRepository.java
  ai/src/main/java/com/zgzg/ai/presentation/DTO/MessageResponseDTO.java
  ai/src/main/java/com/zgzg/ai/presentation/controller/SlackController.java
  common/src/main/java/com/zgzg/common/config/SwaggerConfig.java
  common/src/main/java/com/zgzg/common/response/Code.java
  gateway/src/main/resources/application.yml
Labels: ✨feature

#49 feat: 배송 - 배송 담당자 feign 통신
  delivery/src/main/java/com/zgzg/delivery/application/client/DeliveryPersonClient.java
  delivery/src/main/java/com/zgzg/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/zgzg/delivery/domain/entity/DeliveryRouteLog.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/client/DeliveryPersonClientImpl.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/client/FeignDeliveryPersonClient.java
Labels: ✨feature

#52 refactor: hub 데이터 redis 직렬화 문제 해결
  hub/src/main/java/com/zgzg/hub/application/hub/HubService.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/CreateHubResDTO.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/HubResDTO.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/PageHubsResDTO.java
  hub/src/main/java/com/zgzg/hub/application/hub/res/UpdateHubResDTO.java
  hub/src/main/java/com/zgzg/hub/application/route/service/NaverRouteService.java
  hub/src/main/java/com/zgzg/hub/application/route/service/RouteProcessingService.java
  hub/src/main/java/com/zgzg/hub/config/RedisConfig.java
  hub/src/main/java/com/zgzg/hub/domain/entity/Hub.java
  hub/src/main/java/com/zgzg/hub/presentation/hub/req/CreateHubReqDTO.java
  hub/src/main/java/com/zgzg/hub/presentation/hub/req/UpdateHubReqDTO.java
  hub/src/main/resources/sql/hubData.sql
Labels: ♻️refactor

#53 Feature: 공통 모듈에서 AOP 로깅 기능 구현
  ai/build.gradle
  ai/src/main/java/com/zgzg/ai/AiApplication.java
  ai/src/main/resources/application.yml
  ai/src/main/resources/logback-spring.xml
  common/build.gradle
  common/src/main/java/com/zgzg/common/aop/AopLogConfig.java
  common/src/main/java/com/zgzg/common/aop/AopLogging.java
  company/build.gradle
  company/src/main/java/com/zgzg/company/CompanyApplication.java
  company/src/main/resources/application.yml
  company/src/main/resources/logback-spring.xml
  delivery/build.gradle
  delivery/src/main/java/com/zgzg/delivery/DeliveryApplication.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/client/FeignDeliveryPersonClient.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/dto/HubResponseDTO.java
  delivery/src/main/resources/logback-spring.xml
  gateway/build.gradle
  hub/build.gradle
  hub/src/main/java/com/zgzg/hub/HubApplication.java
  hub/src/main/java/com/zgzg/hub/application/hub/HubService.java
  hub/src/main/resources/logback-spring.xml
  order/build.gradle
  order/src/main/java/com/zgzg/order/OrderApplication.java
  order/src/main/resources/logback-spring.xml
  product/build.gradle
  product/src/main/java/com/zgzg/product/ProductApplication.java
  product/src/main/resources/logback-spring.xml
  sql/data.sql
  user/build.gradle
  user/src/main/resources/logback-spring.xml
Labels: ✨feature

#56 feat: 주문 - 상품, 주문 - 배송 feignClient 통신 구현 및 테스트, 디버깅
  common/src/main/java/com/zgzg/common/response/Code.java
  delivery/src/main/java/com/zgzg/delivery/application/client/DeliveryPersonClient.java
  delivery/src/main/java/com/zgzg/delivery/application/dto/res/DeliveryResponseDTO.java
  delivery/src/main/java/com/zgzg/delivery/application/service/DeliveryService.java
  delivery/src/main/java/com/zgzg/delivery/domain/entity/DeliveryRouteLog.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/client/DeliveryPersonClientImpl.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/client/FeignDeliveryPersonClient.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/client/FeignHubClient.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/client/req/DeliveryUserRequestDTO.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/configuration/OpenFeignConfig.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/dto/HubResDTO.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/dto/HubResponseDTO.java
  delivery/src/main/java/com/zgzg/delivery/infrastructure/repo/DeliveryJpaRepositoryCustomImpl.java
  delivery/src/main/java/com/zgzg/delivery/presentation/DeliveryInternalCotroller.java
  order/src/main/java/com/zgzg/order/application/client/DeliveryClient.java
  order/src/main/java/com/zgzg/order/application/client/ProductClient.java
  order/src/main/java/com/zgzg/order/application/service/OrderService.java
  order/src/main/java/com/zgzg/order/infrastructure/client/DeliveryClientImpl.java
  order/src/main/java/com/zgzg/order/infrastructure/client/FeignDeliveryClient.java
  order/src/main/java/com/zgzg/order/infrastructure/client/FeignProductClient.java
  order/src/main/java/com/zgzg/order/infrastructure/client/ProductClientImpl.java
  order/src/main/java/com/zgzg/order/infrastructure/client/req/ProductStockRequestDTO.java
  order/src/main/java/com/zgzg/order/infrastructure/client/res/ProductResponseDTO.java
  order/src/main/java/com/zgzg/order/infrastructure/dto/CompanyResponseDTO.java
  product/.gitattributes
  product/.gitignore
  product/gradle/wrapper/gradle-wrapper.jar
  product/gradlew
  product/gradlew.bat
  product/settings.gradle
  product/src/main/java/com/zgzg/product/application/service/ProductService.java
  product/src/main/java/com/zgzg/product/presentation/controller/ProductInternalController.java
  user/src/main/java/com/zgzg/user/presentation/controller/DeliveryInternalController.java
Labels: ✨feature
